stop:
  # Default timer in seconds
  timer: 60
  # The title displayed
  # Use {TIME} for timer reference
  # Use {PHASE} for phase in timer
  title: '<transition:#FF0000:#FF8B00:#E4FF00:#00E8FF:#00FF04:{PHASE}>{TIME}</transition>'
  # The subtitle displayed
  # Use {TIME} for timer reference
  # Use {PHASE} for phase in timer
  subtitle: '<red>Server closing...</red>'
  # The message displayed to players, that are kicked before the server stop
  kick-message: '<red>Server closed!</red>'
cancel:
  # The title displayed when stopping is canceled
  title: '<green>Closing canceled!</green>'
  # The subtitle displayed when stopping is canceled
  subtitle: ''
  # Times in milliseconds
  times:
    fade-in: 0
    stay: 2000
    fade-out: 1000